### ISSUE TITLE
Any linux-x86_64 version for Kodi Matrix in the horizon?

### ISSUE THREAD

**Issue by cgcgcgcgcg** [johnny5-is-alive/repository.inputstream.adaptive.testing#1]
Some Live TV addons have inputstream.adaptive.testing as a dependency so, they don't work in eg Arch linux.

**Comment by matthuisman** [comment]
which add-ons?
Inputstream Adaptive in Matrix works 100% and is much further than IA testing.
IA testing will actually be removed soon as its now out of date and no longer needed.

**Comment by cgcgcgcgcg** [comment]
> which add-ons?
> Inputstream Adaptive in Matrix works 100% and is much further than IA testing.
> IA testing will actually be removed soon as its now out of date and no longer needed.

SlyGuy Common and IPTV Merge (SlyGuy repo).

**Comment by matthuisman** [comment]
Latest versions of those shouldn't require IA testing on matrix
